---
# tasks/03_firewall.yml - Firewall Configuration

- name: Allow HTTP traffic (port 80 TCP) - Para redirección o challenges ACME
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp
  when: ansible_facts['os_family'] == "Debian" # Ejemplo para UFW en Debian/Ubuntu

- name: Allow HTTPS traffic (port 443 TCP)
  community.general.ufw:
    rule: allow
    port: "443"
    proto: tcp
  when: ansible_facts['os_family'] == "Debian"

- name: Allow QUIC traffic (port 443 UDP)
  community.general.ufw:
    rule: allow
    port: "443"
    proto: udp
  when: ansible_facts['os_family'] == "Debian"
