Vagrant.configure("2") do |config|
  config.vm.define "proxy" do |proxy|
    proxy.vm.box = "bento/ubuntu-24.04"
    proxy.vm.hostname = "proxy"
    # proxy.vm.network "public_network", ip: "192.168.50.20", bridge: "br0"
    proxy.vm.network "public_network", ip: "192.168.18.181", bridge: "wlo1"

    proxy.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512", "--cpus", "1", "--name", "proxy"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]   
    end
  end

  config.vm.define "web1" do |web|
    web.vm.box = "bento/ubuntu-24.04"
    web.vm.hostname = "web1"
    # web.vm.network "public_network", ip: "192.168.50.21", bridge: "br0"
    web.vm.network "public_network", ip: "192.168.18.182", bridge: "wlo1"

    web.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "1", "--name", "web1"]
    end
  end

  config.vm.define "web2" do |web|
    web.vm.box = "bento/ubuntu-24.04"
    web.vm.hostname = "web2"
    # web.vm.network "public_network", ip: "192.168.50.22", bridge: "br0"
    web.vm.network "public_network", ip: "192.168.18.183", bridge: "wlo1"

    web.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512", "--cpus", "1", "--name", "web2"]
    end
  end

  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = "playbooks/main.yml"
  #   ansible.groups = {
  #     "webservers" => ["web1", "web2"],
  #     "proxys" => ["proxy"],
  #     "nginxservers:children" => ["webservers", "proxys"],
  #   }
  # end
end